---
image: registry.gitlab.com/marcos.cela/ansible.ci:latest

stages:
  - lint

lint-yamlfile:
  stage: lint
  script:
    - yamllint .
lint-ansible:
  stage: lint
  script:
    - ansible-playbook test-playbook.yml --syntax-check -i "localhost,"
